### ISSUE TITLE
allow patch json from file

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonodectl#11]
Adding an argument to the patch function that allows to patch changes from a given json file.

**Comment by ridoo** [comment]
@kilichenko-pixida is working on this

**Comment by kilichenko-pixida** [comment]
@ridoo @mwallschlaeger 
I added this capability and documented  it in the readme - see the [PR](https://github.com/GeoNodeUserGroup-DE/geonodectl/pull/30). 

It will now be possible to give commands like
`geonodectl ds patch 36  --json_path 'path_to/your_json_with_attributes_to_patch.json'` and it also supports patching the attributes, but for that attribute patching to work [this Geonode PR](https://github.com/Thuenen-GeoNode-Development/geonode/pull/4) needs to be merged as well
